name: Go
on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build
    - name: Upload Artifact
      if: matrix.platform != 'windows-latest'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: mfprint-${{ matrix.platform }}
        path: mfprint
    
    - name: Upload Artifact
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: mfprint-${{ matrix.platform }}
        path: mfprint.exe
